# Makefile for compiling LaTeX files with pdflatex

# Set the target file name
TEX_FILE = output.tex
PDF_FILE = output.pdf

# Default target
all: $(PDF_FILE)

# Compile the LaTeX file into PDF
$(PDF_FILE): $(TEX_FILE)
	@echo "Compiling $(TEX_FILE) into $(PDF_FILE)..."
	pdflatex -interaction=nonstopmode $(TEX_FILE)
	@echo "Compilation complete."

# Clean auxiliary files generated by LaTeX
clean:
	@echo "Cleaning up auxiliary files..."
	rm -f *.aux *.log *.out *.toc *.dvi $(PDF_FILE)
	@echo "Cleanup complete."

# Phony targets
.PHONY: all clean

